# Generated by Django 4.2 on 2024-04-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("email_address",), name="unique_email"
            ),
        ),
    ]
